---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "raspberrymatic.fullname" . }}
  labels:
    {{- include "raspberrymatic.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  {{- range $port_name, $port_number := .Values.service.ports.TCP }}
  - name: {{ $port_name }}
    port: {{ $port_number }}
    targetPort: {{ $port_number }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "raspberrymatic.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "raspberrymatic.fullname" . }}-udp
  labels:
    {{- include "raspberrymatic.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
  {{- range $port_name, $port_number := .Values.service.ports.UDP }}
  - name: {{ $port_name }}
    port: {{ $port_number }}
    targetPort: {{ $port_number }}
    protocol: UDP
  {{- end }}
  selector:
    {{- include "raspberrymatic.selectorLabels" . | nindent 4 }}
