blank_issues_enabled: false
contact_links:
  - name: ğŸ‡ºğŸ‡¸ RaspberryMatic Documentation
    url: https://github.com/jens-maus/RaspberryMatic/wiki/en.Home
    about: If you search for answers, please consult the documentation area first.
    
  - name: ğŸ‡ºğŸ‡¸ RaspberryMatic Discussions
    url: https://github.com/jens-maus/RaspberryMatic/discussions
    about: Please ask and answer questions in the RaspberryMatic discussion fora here.

  - name: ğŸ‡©ğŸ‡ª RaspberryMatic Dokumentation
    url: https://github.com/jens-maus/RaspberryMatic/wiki
    about: Wenn Sie nach Antworten suchen, konsultieren Sie bitte zuerst die Dokumentation.
    
  - name: ğŸ‡©ğŸ‡ª RaspberryMatic Diskussionsforum
    url: https://homematic-forum.de/forum/viewforum.php?f=65
    about: Hier kÃ¶nnen Sie bei Problemen Fragen Stellen und Antworten erhalten.
