apiVersion: v2
name: raspberrymatic
description: HomeMatic/homematicIP CCU central based on RaspberryMatic
home: https://raspberrymatic.de/
icon: https://raw.githubusercontent.com/jens-maus/RaspberryMatic/master/home-assistant-addon/icon.png
maintainers:
  - name: Jens Maus
    email: mail@jens-maus.de
    url: https://github.com/jens-maus
  - name: Angel Nunez Mencias
    email: helm@angelnu.com
    url: https://github.com/jens-maus

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: snapshot

annotations:
  artifacthub.io/changes: |
    - Initial Chart release
  artifacthub.io/license: Apache-2.0
