---
name: RaspberryMatic CCU
version: 3.79.6.20241122
slug: raspberrymatic
image: ghcr.io/jens-maus/raspberrymatic
arch:
  - armv7
  - aarch64
  - amd64
description: HomeMatic/homematicIP CCU central based on RaspberryMatic
url: https://github.com/jens-maus/RaspberryMatic/
ingress: true
ingress_stream: true
panel_title: RaspberryMatic
panel_icon: mdi:router-wireless
startup: services
map:
  - type: data
    read_only: false
    path: /usr/local
  - type: backup
    read_only: false
init: false
backup_pre: /bin/sh -c "/bin/echo 'load tclrega.so; rega system.Save()' | /bin/tclsh && /bin/sync"
backup_exclude:
  - "*/tmp/.watchdog"
timeout: 240
devices:
  - /dev/raw-uart
  - /dev/raw-uart1
  - /dev/mmd_hmip
  - /dev/mmd_bidcos
  - /dev/eq3loop
  - /dev/i2c-0
  - /dev/i2c-1
udev: true
usb: true
uart: true
kernel_modules: true
realtime: true
ports:
  22/tcp: null
  80/tcp: null
  443/tcp: null
  2001/tcp: null
  2000/tcp: null
  2010/tcp: null
  9292/tcp: null
  1999/tcp: null
  8181/tcp: null
  42001/tcp: null
  42000/tcp: null
  42010/tcp: null
  49292/tcp: null
  41999/tcp: null
  48181/tcp: null
  9293/tcp: null
  43438/udp: null
  1900/udp: null
  43439/udp: null
  161/udp: null
  8701/tcp: null
  1901/udp: null
  1902/udp: null
  5987/udp: null
  8088/tcp: null
  9099/tcp: null
  10000/udp: null
  48899/udp: null
  49880/udp: null
  8082/tcp: null
  2098/tcp: null
  2099/tcp: null
  8083/tcp: null
  9092/tcp: null
  5435/tcp: null
  2121/tcp: null
  2122/tcp: null
  1883/tcp: null
  8883/tcp: null
  2110/tcp: null
ports_description:
  22/tcp: SSH access (Extern)
  80/tcp: CCU WebUI HTTP (Extern)
  443/tcp: CCU WebUI HTTPS (Extern)
  2001/tcp: HomeMatic-RF XMLRPC (Extern)
  2000/tcp: HomeMatic-Wired XMLRPC (Extern)
  2010/tcp: homematicIP-RF+Wired XMLRPC (Extern)
  9292/tcp: HomeMatic+homematicIP VirtualDevices XMLRPC (Extern)
  1999/tcp: ReGaHss XMLRPC (Extern)
  8181/tcp: ReGaHss HTTP scripting (Extern)
  42001/tcp: HomeMatic-RF XMLRPC-SSL (Extern)
  42000/tcp: HomeMatic-Wired XMLRPC-SSL (Extern)
  42010/tcp: homematicIP-RF+Wired XMLRPC-SSL (Extern)
  49292/tcp: HomeMatic+homematicIP VirtualDevices XMLRPC-SSL (Extern)
  41999/tcp: ReGaHss XMLRPC-SSL (Extern)
  48181/tcp: ReGaHss HTTPS scripting (Extern)
  9293/tcp: homematicIP-RF LAN-Gateway communication (Extern)
  43438/udp: homematicIP-Wired DRAP-Gateway communication (Extern)
  1900/udp: ssdpd auto-discovery (Extern)
  43439/udp: eq3configd NetFinder (Extern)
  161/udp: SNMP monitoring (Extern)
  8701/tcp: CUxD BINRPC (Extern)
  1901/udp: Mediola NeoServer (Extern)
  1902/udp: Mediola NeoServer (Extern)
  5987/udp: Mediola NeoServer (Extern)
  8088/tcp: Mediola NeoServer (Extern)
  9099/tcp: Mediola NeoServer (Extern)
  10000/udp: Mediola NeoServer (Extern)
  48899/udp: Mediola NeoServer (Extern)
  49880/udp: Mediola NeoServer (Extern)
  8082/tcp: CCU-Historian WebUI (Extern)
  2098/tcp: CCU-Historian XMLRPC (Extern)
  2099/tcp: CCU-Historian BINRPC (Extern)
  8083/tcp: CCU-Historian DB-WebUI (Extern)
  9092/tcp: CCU-Historian DB-Port (Extern)
  5435/tcp: CCU-Historian DB-pgPort (Extern)
  2121/tcp: CCU-Jack HTTP (Extern)
  2122/tcp: CCU-Jack HTTPS (Extern)
  1883/tcp: CCU-Jack MQTT (Extern)
  8883/tcp: CCU-Jack MQTT-Secure (Extern)
  2110/tcp: homeputer CL Exec-Engine (Extern)
environment:
  HM_RUNNING_IN_HA: "1"
  HM_HAPROXY_SRC: 172.30.32.2/32
privileged:
  - IPC_LOCK
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_RESOURCE
  - NET_ADMIN
